version: 2
jobs:
  build:
    docker:
      - image: docker:17-git
    working_directory: /workspace
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build and Push Docker Image
          command: |
            export TAG=$(git describe --tags --abbrev=0)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t nshazly/fortune:latest -t nshazly/fortune:$TAG .
            # docker push nshazly/fortune
            echo "complete"
    branches:
      only: circleci-remote-docker-workflow
    # tags:
    #   only: /^v.*/
        