version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Build and Push Docker Image
          command: |
            export TAG=$(git describe --tags --abbrev=0)
            BUILD_TAG=$TAG-$(date +"%s")-$(git rev-parse --short HEAD)-build-$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t nshazly/fortune:latest -t nshazly/fortune:$TAG -t nshazly/fortune:$BUILD_TAG .
            docker push nshazly/fortune
    branches:
      only: circleci-setup
    tags:
      only: '^v.*'
        