version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Build and Push Docker Image
          command: |
            export TAG=$(git describe --tags --abbrev=0)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t nshazly/fortune:latest -t nshazly/fortune:$TAG .
            docker push nshazly/fortune
    branches:
      only: master
    tags:
      only: /^v.*/
        