version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: export TAG=$(git describe --tags --abbrev=0)
      # - setup_remote_docker
      - run: |
          BUILD_TAG=$TAG.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t nshazly/fortune:latest -t nshazly/fortune:$TAG -t nshazly/fortune:$BUILD_TAG .
          docker push nshazly/fortune
    branches:
      only: circlci-setup
        